version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - ${DATA_DIR}/mysql/data/db:/var/lib/mysql #数据文件挂载
      - ${DATA_DIR}/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - ${DATA_DIR}/mysql/log:/var/log/mysql #日志文件挂载
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql # init database
  redis:
    image: redis:5
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ${DATA_DIR}/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
#  nginx:
#    image: nginx:1.10
#    container_name: nginx
#    volumes:
#      - ${DATA_DIR}/nginx/conf:/etc/nginx #配置文件挂载
#      - ${DATA_DIR}/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
#      - ${DATA_DIR}/nginx/log:/var/log/nginx #日志文件挂载
#    ports:
#      - 80:80
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    volumes:
      - ${DATA_DIR}/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - ${DATA_DIR}/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
      - ../sh/create_rabbitmq_mall.sh:/init.sh
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    user: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" #设置使用jvm内存大小
#    volumes:
#      - ${DATA_DIR}/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
#      - ${DATA_DIR}/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    command:
      - sh
      - -c
      - "elasticsearch-plugin list | grep -q analysis-icu
        || elasticsearch-plugin install analysis-icu;
        /usr/local/bin/docker-entrypoint.sh elasticsearch"
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.6.2
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ../elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
  mongo:
    image: mongo:4.2.5
    container_name: mongo
    volumes:
      - ${DATA_DIR}/mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017
  consul:
    image: consul:1.8.8
    container_name: consul-registry
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500